WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
  File "list_opcodes.py", line 292, in <module>
    main( )
  File "list_opcodes.py", line 276, in main
    records = find_dates(stream)
  File "list_opcodes.py", line 223, in find_dates
    assert datetime is not None, "\n%s" % lib.hexdump(bolus)
AssertionError: 
0000   0x6c 0x2e 0x00 0x05 0x0c 0x00 0xe8 0x00    l.......
0008   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0010   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0018   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0020   0x00 0x00 0x00 0x00 0x00 0x00 0x07 0x00    ........
0028   0x00 0x00 0x00 0x2f 0x00 0x6c 0x2f 0x00    .../.l/.
0030   0x05 0x0c 0x00 0xe8 0x00 0x00 0x00 0x00    ........
0038   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0040   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0048   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0050   0x00 0x00 0x00 0x07 0x00 0x00 0x00 0x00    ........
0058   0x30 0x00 0x6c 0x30 0x00 0x05 0x0c 0x00    0.l0....
0060   0xe8 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0068   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0070   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0078   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0080   0x07 0x00 0x00 0x00 0x00 0x31 0x00 0x6c    .....1.l
